
name: Run Test Suite

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  flake8-linter-test:
    name: Flake 8 Linter Test
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt

    - name: Run Linter Test
      run: flake8 ui_kindlerevenant.py